### ISSUE TITLE
dependency versions

### ISSUE THREAD

**Issue by gigilx** [ArthurDelannoyazerty/Mesh-simplification-GNN#2]
May I ask if you could provide dependency versions for each package?

**Comment by ArthurDelannoyazerty** [comment]
Hello,
Here are the version of each librairies I use :
- trimesh 4.4.1
- numpy 1.22.4
- torch 2.2.0
- vtkplotlib 2.1.0
- tqdm 4.66.4
- mesh : not idea (lastest I think)
- matplotlib 3.8.0
- mpl_toolkits : no idea
- networkx 3.1
- trimesh 4.4.1
- torch_geometric 2.5.3

**Comment by ArthurDelannoyazerty** [comment]
Hello,Here are the version of each librairies I use : 
- trimesh 4.4.1
- numpy 1.22.4
- torch 2.2.0
- vtkplotlib 2.1.0
- tqdm 4.66.4
- mesh : not idea (lastest I think)
- matplotlib 3.8.0
- mpl_toolkits : no idea
- networkx 3.1
- trimesh 4.4.1
- torch_geometric 2.5.3

**Comment by gigilx** [comment]
That's great, thank you very much
